"""Pluggable embedding provider abstraction.

The default provider (``HashingEmbeddingProvider``) is a deterministic,
offline, dependency-free bag-of-words hashing embedding. It requires no API
key and no network access, so retrieval works identically in CI, offline
development, and the live demo. It behaves like a crude TF-style embedding:
documents that share vocabulary get high cosine similarity, which is
sufficient to demonstrate genuine hybrid retrieval without pretending to be a
state-of-the-art neural embedding.

An OpenAI-compatible provider is available for higher-quality embeddings when
OPENAI_API_KEY is configured; the app must not require it to function.
"""
from __future__ import annotations

import hashlib
import math
import re
from abc import ABC, abstractmethod

import httpx

from app.core.config import Settings, get_settings

_TOKEN_RE = re.compile(r"[a-zA-Z]{2,}")

_STOPWORDS = {
    "the", "and", "for", "are", "with", "that", "this", "from", "was", "were",
    "have", "has", "had", "not", "but", "can", "may", "its", "into", "such",
    "of", "in", "on", "to", "a", "an", "is", "be", "as", "by", "or", "it",
    "which", "these", "those", "their", "than", "also", "we", "our",
}


class EmbeddingProvider(ABC):
    @abstractmethod
    def embed(self, text: str) -> list[float]: ...

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        return [self.embed(t) for t in texts]


class HashingEmbeddingProvider(EmbeddingProvider):
    def __init__(self, dimensions: int = 256):
        self.dimensions = dimensions

    def _tokenize(self, text: str) -> list[str]:
        tokens = [t.lower() for t in _TOKEN_RE.findall(text)]
        return [t for t in tokens if t not in _STOPWORDS]

    @staticmethod
    def _stable_hash(token: str) -> int:
        # Deterministic across processes/runs, unlike Python's built-in hash()
        # for strings, which is randomized per-process (PYTHONHASHSEED) and
        # would silently make embeddings generated by different processes
        # (e.g. the seed script vs. the running server) incomparable.
        digest = hashlib.md5(token.encode("utf-8")).hexdigest()
        return int(digest, 16)

    def embed(self, text: str) -> list[float]:
        vec = [0.0] * self.dimensions
        tokens = self._tokenize(text)
        if not tokens:
            return vec
        for tok in tokens:
            h = self._stable_hash(tok)
            idx = h % self.dimensions
            sign = 1.0 if (h // self.dimensions) % 2 == 0 else -1.0
            vec[idx] += sign
        norm = math.sqrt(sum(v * v for v in vec))
        if norm > 0:
            vec = [v / norm for v in vec]
        return vec


class OpenAICompatibleEmbeddingProvider(EmbeddingProvider):
    def __init__(self, settings: Settings):
        self.settings = settings
        self._client = httpx.Client(
            base_url=settings.openai_base_url,
            headers={"Authorization": f"Bearer {settings.openai_api_key}"},
            timeout=20.0,
        )

    def embed(self, text: str) -> list[float]:
        resp = self._client.post(
            "/embeddings", json={"model": self.settings.openai_embedding_model, "input": text}
        )
        resp.raise_for_status()
        return resp.json()["data"][0]["embedding"]


def cosine_similarity(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


_provider: EmbeddingProvider | None = None


def get_embedding_provider() -> EmbeddingProvider:
    global _provider
    if _provider is not None:
        return _provider
    settings = get_settings()
    if settings.embedding_provider == "openai" and settings.openai_api_key:
        _provider = OpenAICompatibleEmbeddingProvider(settings)
    else:
        _provider = HashingEmbeddingProvider(dimensions=settings.embedding_dimensions)
    return _provider
