"""initial schema

Revision ID: 0b8199e6eacd
Revises: 
Create Date: 2026-09-16 16:31:04.031952

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b8199e6eacd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interventions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_metrics', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('ecosystem_context', sa.JSON(), nullable=False),
    sa.Column('source_claim_ids', sa.JSON(), nullable=False),
    sa.Column('water_sensitivity', sa.String(length=20), nullable=True),
    sa.Column('typical_time_horizon', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_nodes',
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('scientific_sources',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text_available', sa.Boolean(), nullable=False),
    sa.Column('license_notes', sa.String(length=400), nullable=True),
    sa.Column('ingestion_status', sa.String(length=30), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ecosystem_context', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_chunks',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environmental_profiles',
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ecosystem_type', sa.String(length=120), nullable=True),
    sa.Column('land_use_type', sa.String(length=120), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_organic_carbon', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.Column('rainfall_mm_year', sa.Float(), nullable=True),
    sa.Column('rainfall_qualitative', sa.String(length=20), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('biodiversity_indicators', sa.JSON(), nullable=False),
    sa.Column('human_impact_indicators', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=120), nullable=True),
    sa.Column('unit_metadata', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('uncertainty_metadata', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientific_claims',
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=30), nullable=False),
    sa.Column('evidence_strength', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('evidence_chunk_id', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scientific_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assessment_summary', sa.Text(), nullable=False),
    sa.Column('known_facts', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('variables_considered', sa.JSON(), nullable=False),
    sa.Column('reasoning_paths', sa.JSON(), nullable=False),
    sa.Column('overall_limitations', sa.JSON(), nullable=False),
    sa.Column('previous_assessment_id', sa.String(), nullable=True),
    sa.Column('diff_from_previous', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['previous_assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['environmental_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environmental_observations',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['environmental_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_edges',
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('source_claim_id', sa.String(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=20), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_claim_id'], ['scientific_claims.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('intervention_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('what_to_do', sa.Text(), nullable=False),
    sa.Column('why_it_may_work', sa.Text(), nullable=False),
    sa.Column('impacted_metrics', sa.JSON(), nullable=False),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('feasibility_constraints', sa.JSON(), nullable=False),
    sa.Column('trade_offs', sa.JSON(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('heuristic_score', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['environmental_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_plans',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('baseline_requirement', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('measurement_method', sa.Text(), nullable=False),
    sa.Column('measurement_frequency', sa.String(length=80), nullable=False),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('expected_direction', sa.String(length=20), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoring_plans')
    op.drop_table('recommendations')
    op.drop_table('knowledge_edges')
    op.drop_table('environmental_observations')
    op.drop_table('assessments')
    op.drop_table('scientific_claims')
    op.drop_table('messages')
    op.drop_table('environmental_profiles')
    op.drop_table('evidence_chunks')
    op.drop_table('conversations')
    op.drop_table('user_sessions')
    op.drop_table('scientific_sources')
    op.drop_table('knowledge_nodes')
    op.drop_table('interventions')
    # ### end Alembic commands ###
