"""add evidence_strength_summary and data_completeness to recommendations

Revision ID: 666d1a4d61b0
Revises: 0b8199e6eacd
Create Date: 2026-09-18 08:46:02.100345

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '666d1a4d61b0'
down_revision: Union[str, None] = '0b8199e6eacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default lets this apply cleanly against a table that already has
    # rows (e.g. a running deployment) rather than failing a NOT NULL add.
    op.add_column(
        'recommendations',
        sa.Column('evidence_strength_summary', sa.String(length=20), nullable=False, server_default='hypothesis'),
    )
    op.add_column(
        'recommendations',
        sa.Column('data_completeness', sa.Float(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'data_completeness')
    op.drop_column('recommendations', 'evidence_strength_summary')
    # ### end Alembic commands ###
