/**
 * Utility functions for exporting ecological assessments and evidence graphs
 * into formatted Markdown for research reports, grant applications, and team sharing.
 */

import { AssessmentOut } from "../types/api";

export function formatAssessmentAsMarkdown(assessment: AssessmentOut): string {
  const lines: string[] = [
    `# Ecological Assessment Report`,
    `**Generated by EcoSynapse AI**`,
    `**Assessment ID:** \`${assessment.id}\``,
    `**Version:** \`v${assessment.version}\``,
    `**Date:** ${new Date(assessment.created_at).toLocaleString()}`,
    ``,
    `---`,
    ``,
    `## 1. Executive Summary & Synthesis`,
    assessment.assessment_summary || "No synthesis text available.",
    ``,
    `## 2. Recommended Interventions`,
  ];

  if (assessment.recommendations && assessment.recommendations.length > 0) {
    assessment.recommendations.forEach((rec, idx) => {
      lines.push(`### ${idx + 1}. ${rec.title || "Intervention"}`);
      lines.push(`- **Action Plan:** ${rec.what_to_do}`);
      lines.push(`- **Ecological Mechanism:** ${rec.why_it_may_work}`);
      lines.push(`- **Confidence:** ${rec.confidence?.level?.toUpperCase()} — ${rec.confidence?.reason || ""}`);
      if (rec.feasibility_constraints && rec.feasibility_constraints.length > 0) {
        lines.push(`- **Feasibility Constraints:**`);
        rec.feasibility_constraints.forEach((c) => lines.push(`  - ${c}`));
      }
      if (rec.trade_offs && rec.trade_offs.length > 0) {
        lines.push(`- **Ecological Trade-offs:**`);
        rec.trade_offs.forEach((t) => lines.push(`  - ${t}`));
      }
      if (rec.evidence && rec.evidence.length > 0) {
        lines.push(`- **Citations & Evidence:**`);
        rec.evidence.forEach((ev) => {
          lines.push(`  - [${ev.source_title || "Source"}]: ${ev.claim} *(Strength: ${ev.evidence_status || "cited"})*`);
        });
      }
      lines.push(``);
    });
  } else {
    lines.push(`*No specific interventions recommended.*`);
    lines.push(``);
  }

  lines.push(`## 3. Unknowns & Knowledge Gaps`);
  if (assessment.unknowns && assessment.unknowns.length > 0) {
    assessment.unknowns.forEach((u) => lines.push(`- ${u}`));
  } else {
    lines.push(`*No critical unknowns identified.*`);
  }

  return lines.join("\n");
}

export async function copyMarkdownToClipboard(markdownText: string): Promise<boolean> {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(markdownText);
      return true;
    }
    return false;
  } catch {
    return false;
  }
}
